name: bump

on:
    push:
        paths:
            - 'package.json'
        branches: [master]
    workflow_dispatch:

jobs:
    publish-client:
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: read
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
            - run: yarn
            - run: yarn build
            - run: npm publish --access=public
              working-directory: .
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
